export { rebuildVersionedLink } from './rebuildVersionedLink'
export { resolveVersionFromCurrentRoute } from './resolveVersionFromCurrentRoute'
export { useVersionedLink } from './useVersionedLink'
export { useVersionManager } from './useVersionManager'
export { useVersionDropdown } from './useVersionDropdown'
export { usePlatformDropdown } from './usePlatformDropdown'